---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
```

```{r}
data("instacart")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart |> 
  filter(department != "missing") |> 
  mutate(
    department = fct_reorder(department, days_since_prior_order)) |> 
  plot_ly(x = ~ department, y = ~ days_since_prior_order, color = ~ department,
          type = "box")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart |> 
  group_by(department) |> 
  summarize(orders = n_distinct(order_id)) |> 
  plot_ly(
    x = ~orders, y = ~ fct_reorder(department, orders),
    type = "bar"
  )
```

### Chart C

```{r}
instacart |> 
  group_by(order_hour_of_day) |> 
  summarize(n = n_distinct(order_id)) |> 
  plot_ly(x = ~ order_hour_of_day, y = ~ n, type = "scatter", 
          mode = "markers", alpha = 0.5)
```

